esphome:
  name: esphome-web-4ac0cf
  friendly_name: Motion-Sensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PcZDiDIGluL9Y2p6OpJCbWRikz0csoOnuwzeLPewfCs="
  
ota:
  


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-4Ac0Cf"
    password: "KmQOLQP4fOoZ"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "Motion Sensor"
    device_class: motion 
